### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by rameshkumar-rk** [arun-kataria/image-file-resize#1]
I am confused about how can i use this library

can i get the sample code

**Comment by arun-kataria** [comment]
It is mention in the Example section. Please check that.

First, you need to install this NPM package them import or require it where ever you want. Like that, 


    import convert from 'image-file-resize';
 
    convert({ 
        file: e.target.files[0],  
        width: 600, 
        height: 400, 
        type: 'jpeg'
        }).then(resp => {
            // Response contain compressed and resized file
        }).catch(error => {
             // Error
        })
