### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by hamelgoyal** [arun-kataria/image-file-resize#3]
I tried using this package in my ionic angular project. But nothing is working. No error no result. Please help. Sample code below:

```
convert({ 
                  file: file,  
                  width: 2738, 
                  height: 1800, 
                  type: 'jpeg'
                  }).then(resp => {
                     console.log(resp);
                  }).catch(error => {
                  console.log(error);
               })
```

**Comment by arun-kataria** [comment]
Hi @hamelgoyal 

Could you please check your file extension should contain  'jpg', 'gif', 'bmp', 'png', 'jpeg'. Also you can verify from the [link](https://react-rggk21.stackblitz.io/).
